-- USER SQL
CREATE USER aqdemo IDENTIFIED BY aqdemo 
DEFAULT TABLESPACE aqdemo
TEMPORARY TABLESPACE temp;

-- QUOTAS
ALTER USER aqdemo QUOTA UNLIMITED ON aqdemo;

-- ROLES
GRANT connect TO aqdemo ;
GRANT resource TO aqdemo ;
ALTER USER aqdemo DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES
GRANT DEBUG CONNECT SESSION TO aqdemo ;
GRANT ALTER SESSION TO aqdemo ;
GRANT CREATE MATERIALIZED VIEW TO aqdemo ;
GRANT CREATE VIEW TO aqdemo ;
GRANT SELECT ANY DICTIONARY TO aqdemo ;
GRANT FLASHBACK ARCHIVE ADMINISTER TO aqdemo ;

-- OBJECT PRIVILEGES
GRANT EXECUTE ON dbms_aqadm TO aqdemo;
GRANT EXECUTE ON dbms_aq TO aqdemo;
GRANT EXECUTE ON dbms_aqin to aqdemo;
